### ISSUE TITLE
Intégration Page Conseils

### ISSUE THREAD

**Issue by omayma96** [omayma96/projet-C2N3-C3N3#3]
- Convertissez le design graphique de la page Conseil en un code HTML CSS compressé et Compatible avec tous les navigateur en utilisant NPM, SASS.

- Analysez bien le Design

- Intégrez votre code html en respectant la structure que vous venez d’imaginer

- Pensez bien à votre stratégie de découpage.

- Nommez vos blocs de façon sémantique en utilisant le concept BEM

- Incluez un reset css dans le header de votre page html.

- [x]  Intégration section Informations

 

- [x] Intégration section Symptômes

- [x]  Intégration Recommandations officielles

- [x]  Intégration section Hero Footer contenant la section Test et le footer

**Notez Bien :**
Cette peut être élaborer qu'avec du Flexbox et même sans média queries.
💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯

**Comment by omayma96** [comment]
cette page est terminéé

**Comment by youssefbm** [comment]
Les images ne s'affichent pas. Essayez de créer un dossier image  dans le dossier starter. Ajoutez dedans les images dont vous avez besoin. Renommez les images. Mettez à jour le chemin dans l'attribut "src" des balises d'images.

**Comment by omayma96** [comment]
la page conseil est prête avec les remarques mentionnées. 
N.B : le site n'est pas responsive

**Comment by omayma96** [comment]
le page conseil est terminée, elle est responsive
